name: pypi-template
on:
  push:
    branches: ['pypi-template']
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      FLIT_USERNAME: ${{ secrets.PYPI_USER }}
      FLIT_PASSWORD: ${{ secrets.PYPI_PASS }}
    steps:
      - uses: actions/checkout@v3
      - name: start build
        run: |
          ./scripts/build.sh